import { useState } from "react";
import { useScanInput, useScanOutput } from "@/hooks/use-scan";
import { ScannerForm } from "@/components/ScannerForm";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default function Dashboard() {
  const [activeTab, setActiveTab] = useState("input");
  
  const scanInput = useScanInput();
  const scanOutput = useScanOutput();

  return (
    <div className="min-h-screen bg-[#FDFBF9]">
      {/* Header */}
      <header className="bg-[#FCF9F6] border-b border-stone-200">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex flex-col">
            <span className="font-bold text-xl text-stone-900 tracking-tight">Promptinel</span>
            <span className="text-[10px] text-stone-500 uppercase tracking-[0.2em] font-medium leading-none">
              AI Security Infrastructure
            </span>
          </div>
          <div className="hidden md:block text-sm font-medium text-stone-600">
            Real-Time AI Guardrails for Secure LLM Applications
          </div>
          <div className="flex items-center gap-4">
            <div className="h-2 w-2 rounded-full bg-stone-400 animate-pulse" />
            <span className="text-xs font-semibold text-stone-500 uppercase tracking-widest">System Active</span>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-12">
        <Tabs defaultValue="input" value={activeTab} onValueChange={setActiveTab} className="space-y-10">
          <div className="flex items-center justify-between border-b border-stone-200 pb-1">
            <TabsList className="bg-transparent h-auto p-0 gap-8">
              <TabsTrigger 
                value="input" 
                className="relative h-12 rounded-none border-b-2 border-transparent bg-transparent px-0 pb-3 pt-2 font-semibold text-stone-500 transition-none data-[state=active]:border-primary data-[state=active]:text-primary data-[state=active]:shadow-none"
              >
                Input Guardrail
              </TabsTrigger>
              <TabsTrigger 
                value="output"
                className="relative h-12 rounded-none border-b-2 border-transparent bg-transparent px-0 pb-3 pt-2 font-semibold text-stone-500 transition-none data-[state=active]:border-primary data-[state=active]:text-primary data-[state=active]:shadow-none"
              >
                Output Guardrail
              </TabsTrigger>
            </TabsList>
          </div>

          <div className="max-w-5xl">
            <TabsContent value="input" className="mt-0 outline-none">
              <div className="mb-8">
                <h2 className="text-2xl font-bold text-stone-900 mb-2 font-serif">AI Security Scan</h2>
                <p className="text-stone-500 max-w-2xl leading-relaxed">
                  Analyze AI inputs and outputs for prompt injections, data leaks, and policy violations before deployment.
                </p>
              </div>
              <ScannerForm
                type="input"
                title="Input Guardrail"
                description="Detects prompt injection attempts, jailbreaks, and malicious system overrides before they reach your LLM."
                placeholder='Enter prompt, user input, or LLM response here...'
                onScan={(data) => scanInput.mutateAsync(data)}
                isPending={scanInput.isPending}
              />
            </TabsContent>

            <TabsContent value="output" className="mt-0 outline-none">
              <div className="mb-8">
                <h2 className="text-2xl font-bold text-stone-900 mb-2 font-serif">AI Security Scan</h2>
                <p className="text-stone-500 max-w-2xl leading-relaxed">
                  Analyze AI inputs and outputs for prompt injections, data leaks, and policy violations before deployment.
                </p>
              </div>
              <ScannerForm
                type="output"
                title="Output Guardrail"
                description="Scans model responses for PII leaks (emails, phones) and unsafe content generated by the AI."
                placeholder='Enter prompt, user input, or LLM response here...'
                onScan={(data) => scanOutput.mutateAsync(data)}
                isPending={scanOutput.isPending}
              />
            </TabsContent>
          </div>
        </Tabs>
      </main>

      <footer className="max-w-7xl mx-auto px-6 py-12 border-t border-stone-200 mt-20">
        <div className="flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="text-sm text-stone-500 font-medium uppercase tracking-widest">
            Promptinel v1 • AI Security Infrastructure
          </div>
          <div className="flex gap-8">
            <a href="#" className="text-xs font-semibold text-stone-400 hover:text-stone-600 transition-colors uppercase tracking-widest">Docs</a>
            <a href="#" className="text-xs font-semibold text-stone-400 hover:text-stone-600 transition-colors uppercase tracking-widest">API</a>
            <a href="#" className="text-xs font-semibold text-stone-400 hover:text-stone-600 transition-colors uppercase tracking-widest">Contact</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
